In [11]:
import sys, os
sys.path.append(os.pardir)
from dataset.mnist import load_mnist
import numpy as np

(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, one_hot_label=True)

print(x_train.shape)
print(t_train.shape)

train_size = x_train.shape[0]
batch_size = 10
batch_mask = np.random.choice(train_size, batch_size)
print(batch_mask)

# reshape かくにん
y = np.array([0, 1, 2, 3])
print(y.ndim)
print(y.shape)
y = y.reshape(1, y.size)
print(y.shape)

(60000, 784)
(60000, 10)
[ 4355   355 56007 29499  5543 57991 28973 58231 46469 51305]
1
(4,)
(1, 4)


In [60]:
# 交差エントロピー誤差
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
    
    batch_size = y.shape[0]
    return -np.sum(t * np.log(y)) / batch_size
    # one-hot表現ではなくラベルで教師データが与えられたときは
    #return -np.sum(t * np.log(y[np.arange(batch_size), t])) / batch_size

# np.arange あたりのかくにん
# y = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
# t = np.array([[0, 1, 2, 3], [4, 5, 6, 7]]) # これはうまくいかない
y = np.array([[0, 1, 2, 3, 4, 5, 6, 7]])
t = np.array([[7, 1, 2, 3, 4, 5, 6, 0]])
print(y.shape)
print(t.shape)
print(np.array([1,2]).shape)

batch_size = y.shape[0]
print(batch_size)
a = np.arange(batch_size)
print(y[a].shape)
print(y[a])
v = y[a, t]
print(v)


(1, 8)
(1, 8)
(2,)
1
(1, 8)
[[0 1 2 3 4 5 6 7]]
[[7 1 2 3 4 5 6 0]]
